#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 19 RBAC 
# Url: https://ithelp.ithome.com.tw/articles/10195944
# Licence: MIT
#####################################

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]